import './globals.css';
import { Montserrat } from 'next/font/google';
import { LayoutProvider } from '@/components/LayoutProvider';
import ContextProvider from '@/components/ContextProvider';
import 'react-toastify/dist/ReactToastify.min.css';
import { ToastContainer } from 'react-toastify';

const montserrat = Montserrat({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ContextProvider>
          <LayoutProvider>{children}</LayoutProvider>
        </ContextProvider>
      </body>
    </html>
  );
}
